// Shared data for all three Velocity Whitepaper directions.
// Single source of truth — each direction reads from window.VW.

window.VW = (function () {
  const stats = {
    apps: 1400,
    repos: 3800,
    loc: 466_000_000,
    ministries: 27,
    debt_dollars: 2_100_000_000,
    annual_carry: 340_000_000,
    dependencies: 281_400,
    platforms: 17,
    avg_app_age_years: 14.3,
    eol_systems_pct: 38,
    engineers_on_payroll: 2150,
  };

  // Velocity Whitepaper series. Volume / number / status are intentional —
  // gives the library an archive feel.
  const whitepapers = [
    {
      id: 'wp-01',
      vol: 'I',
      num: '01',
      title: 'The Velocity Thesis',
      subtitle: 'Why agentic AI is the only viable path to clear $2.1B in application debt within a decade.',
      track: 'Strategy',
      authors: ['Ministry of Technology and Innovation', 'Velocity Working Group'],
      published: '2026-03-04',
      reading_min: 22,
      status: 'Published',
      tags: ['thesis', 'economics', 'policy'],
      pages: 41,
      abstract: 'A first-principles argument for replacing project-based modernization with continuous, agent-led remediation. We quantify the cost of carry across Alberta\u2019s application portfolio, model three scenarios, and explain why human-only approaches plateau at a remediation rate roughly two orders of magnitude below need.',
      sections: [
        { n: '01', title: 'The carry cost of inaction' },
        { n: '02', title: 'Why human-only doesn\u2019t scale' },
        { n: '03', title: 'The agentic alternative' },
        { n: '04', title: 'Scenario modeling: 2026\u20132035' },
        { n: '05', title: 'Risks, dependencies, and second-order effects' },
        { n: '06', title: 'Recommended program structure' },
      ],
    },
    {
      id: 'wp-02',
      vol: 'I',
      num: '02',
      title: 'Codebase Cartography',
      subtitle: 'Mapping 3,800 repositories and 466 million lines of code with deep-context indexing.',
      track: 'Discovery',
      authors: ['Platform Engineering', 'Data Architecture Branch'],
      published: '2026-03-18',
      reading_min: 34,
      status: 'Published',
      tags: ['indexing', 'graph', 'embeddings'],
      pages: 58,
      abstract: 'Before any agent can act, the estate must be legible. We describe a layered indexing strategy \u2014 lexical, semantic, symbolic, and behavioural \u2014 that produces a queryable knowledge graph spanning every repository the province owns. The graph is the substrate on which every downstream Velocity agent operates.',
      sections: [
        { n: '01', title: 'Repository discovery and consent' },
        { n: '02', title: 'The four-layer index' },
        { n: '03', title: 'Cross-repo symbol resolution' },
        { n: '04', title: 'Behavioural traces from production' },
        { n: '05', title: 'The Cartography Query Language (CQL)' },
        { n: '06', title: 'Storage, freshness, and access control' },
      ],
    },
    {
      id: 'wp-03',
      vol: 'II',
      num: '03',
      title: 'The Agentic Operating Model',
      subtitle: 'Multi-agent orchestration across 27 ministries, with policy-aware routing and budgeted autonomy.',
      track: 'Architecture',
      authors: ['Velocity Architecture Council'],
      published: '2026-04-02',
      reading_min: 41,
      status: 'Published',
      tags: ['agents', 'orchestration', 'governance'],
      pages: 72,
      abstract: 'A reference architecture for an agent mesh that respects ministry sovereignty, policy boundaries, and security baselines. We define five agent classes, a budget-bound autonomy ledger, and the inter-agent message contract that allows specialists to compose without a global supervisor becoming a bottleneck.',
      sections: [
        { n: '01', title: 'Agent classes and their guarantees' },
        { n: '02', title: 'The autonomy ledger' },
        { n: '03', title: 'Ministry-scoped namespaces' },
        { n: '04', title: 'Inter-agent contracts (IAC v1)' },
        { n: '05', title: 'Failure modes and circuit breakers' },
        { n: '06', title: 'Reference deployment topology' },
      ],
    },
    {
      id: 'wp-04',
      vol: 'II',
      num: '04',
      title: 'Provenance and Trust',
      subtitle: 'Maintaining cryptographic audit trails across autonomous code modification at scale.',
      track: 'Governance',
      authors: ['Office of the Chief Information Security Officer'],
      published: '2026-04-22',
      reading_min: 27,
      status: 'Published',
      tags: ['security', 'audit', 'compliance'],
      pages: 48,
      abstract: 'Public trust requires that every line an agent writes is traceable to a decision, a model version, and a human accountable party. We specify a provenance protocol that ties every commit to a signed reasoning record, supports retrospective revocation, and integrates with Treasury Board\u2019s audit framework.',
      sections: [
        { n: '01', title: 'The provenance triad' },
        { n: '02', title: 'Signed reasoning records' },
        { n: '03', title: 'Revocation, rollback, and remediation' },
        { n: '04', title: 'Integration with the audit framework' },
        { n: '05', title: 'Public transparency layer' },
      ],
    },
    {
      id: 'wp-05',
      vol: 'III',
      num: '05',
      title: 'Legacy Modernization at Scale',
      subtitle: 'COBOL, PowerBuilder, and Forms 6i \u2014 migrating the systems no one wanted to touch.',
      track: 'Modernization',
      authors: ['Legacy Systems Group', 'Velocity Pattern Library'],
      published: '2026-05-06',
      reading_min: 38,
      status: 'Published',
      tags: ['cobol', 'mainframe', 'migration'],
      pages: 64,
      abstract: 'Thirty-eight percent of the province\u2019s portfolio runs on platforms whose vendor support ended before 2015. We describe the Velocity migration loop: an agent-led process that produces verified, behaviourally-equivalent replacements without freezing the original system, with case studies from three ministry pilots.',
      sections: [
        { n: '01', title: 'The thirty-eight-percent problem' },
        { n: '02', title: 'Behavioural equivalence as the contract' },
        { n: '03', title: 'The Velocity migration loop' },
        { n: '04', title: 'Case: Vital Statistics' },
        { n: '05', title: 'Case: Land Titles' },
        { n: '06', title: 'Case: Income Support disbursement' },
      ],
    },
    {
      id: 'wp-06',
      vol: 'III',
      num: '06',
      title: 'The Cost of Carry',
      subtitle: 'Quantifying $340M/yr in unrecognized maintenance burden across 1,400 applications.',
      track: 'Economics',
      authors: ['Treasury Board Analytics', 'Velocity Economics Cell'],
      published: '2026-05-19',
      reading_min: 19,
      status: 'Published',
      tags: ['economics', 'measurement'],
      pages: 32,
      abstract: 'Technical debt is a financial liability that the province does not currently book. We propose a measurement framework that translates code-level signals (cyclomatic risk, dependency staleness, incident frequency) into dollar-denominated carry cost per application, suitable for inclusion in budget submissions.',
      sections: [
        { n: '01', title: 'Why debt isn\u2019t on the balance sheet' },
        { n: '02', title: 'The Carry Index' },
        { n: '03', title: 'From signal to dollars' },
        { n: '04', title: 'Portfolio-level rollups' },
        { n: '05', title: 'Implications for budget cycles' },
      ],
    },
    {
      id: 'wp-07',
      vol: 'IV',
      num: '07',
      title: 'Sovereign AI Infrastructure',
      subtitle: 'On-premise model deployment for citizen-data workloads, with FedRAMP-equivalent isolation.',
      track: 'Infrastructure',
      authors: ['Cloud and Compute Branch'],
      published: '2026-06-03',
      reading_min: 31,
      status: 'Forthcoming',
      tags: ['infrastructure', 'sovereignty', 'security'],
      pages: 54,
      abstract: 'Velocity\u2019s agents must operate on data that cannot leave provincial jurisdiction. We describe the sovereign inference fabric \u2014 a tiered deployment of open-weight models in three Alberta data centres, with a routing layer that respects data classification at the row level.',
      sections: [
        { n: '01', title: 'The data-classification routing problem' },
        { n: '02', title: 'Three-tier inference fabric' },
        { n: '03', title: 'Model selection and lifecycle' },
        { n: '04', title: 'Capacity planning to 2030' },
        { n: '05', title: 'Disaster posture' },
      ],
    },
    {
      id: 'wp-08',
      vol: 'IV',
      num: '08',
      title: 'Human-in-the-Loop Governance',
      subtitle: 'Review patterns, escalation gates, and the engineer-as-supervisor model.',
      track: 'Operations',
      authors: ['Velocity Practice Group'],
      published: '2026-06-17',
      reading_min: 25,
      status: 'Forthcoming',
      tags: ['operations', 'review', 'workflow'],
      pages: 44,
      abstract: 'Even highly autonomous agents need supervision \u2014 but at scale, conventional code review breaks down. We describe a governance pattern in which engineers act as supervisors of populations of agent-generated changes, with statistical sampling, gated escalation, and incident-driven re-review.',
      sections: [
        { n: '01', title: 'Why per-change review fails at scale' },
        { n: '02', title: 'The supervisor pattern' },
        { n: '03', title: 'Statistical sampling and tiered gates' },
        { n: '04', title: 'Incident replay and re-review' },
        { n: '05', title: 'Training the supervisors' },
      ],
    },
    {
      id: 'wp-09',
      vol: 'V',
      num: '09',
      title: 'Continuous Migration',
      subtitle: 'Replacing batch modernization projects with perpetual, low-amplitude remediation.',
      track: 'Strategy',
      authors: ['Velocity Working Group'],
      published: '2026-07-08',
      reading_min: 21,
      status: 'Draft',
      tags: ['strategy', 'operations'],
      pages: 36,
      abstract: 'The largest source of debt is the gap between system change and its consequences being understood. We propose abolishing the modernization project as a unit of work and replacing it with a continuous flow model, in which every system is always partway through being remediated.',
      sections: [
        { n: '01', title: 'The project as a debt instrument' },
        { n: '02', title: 'Continuous flow, defined' },
        { n: '03', title: 'Funding implications' },
        { n: '04', title: 'Vendor and procurement effects' },
      ],
    },
    {
      id: 'wp-10',
      vol: 'V',
      num: '10',
      title: 'The Citizen Outcomes Framework',
      subtitle: 'Measuring debt reduction by service-to-citizen impact rather than lines of code.',
      track: 'Measurement',
      authors: ['Service Alberta', 'Velocity Measurement Cell'],
      published: '2026-07-22',
      reading_min: 18,
      status: 'Draft',
      tags: ['measurement', 'service-design'],
      pages: 28,
      abstract: 'A debt reduction program that optimizes for engineer-visible metrics will produce engineer-visible improvements. We close the series by tying every Velocity output back to a measurable citizen outcome, with a worked example for the income-support payment cycle.',
      sections: [
        { n: '01', title: 'The vanity-metric trap' },
        { n: '02', title: 'Citizen-outcome trees' },
        { n: '03', title: 'Worked example: income-support disbursement' },
        { n: '04', title: 'Closing the loop' },
      ],
    },
  ];

  // The agentic architecture: layered, with flow.
  // Each node has {id, layer, label, sub, throughput} where layer is the y-band.
  const architecture = {
    layers: [
      { id: 'discover', label: 'Discovery', sub: 'Estate ingestion' },
      { id: 'analyze',  label: 'Analysis',  sub: 'Comprehension & risk' },
      { id: 'plan',     label: 'Planning',  sub: 'Strategy & sequencing' },
      { id: 'implement',label: 'Implementation', sub: 'Code changes' },
      { id: 'verify',   label: 'Verification', sub: 'Behavioural equivalence' },
      { id: 'govern',   label: 'Governance', sub: 'Human gates & audit' },
      { id: 'deploy',   label: 'Deployment', sub: 'Rollout & rollback' },
    ],
    agents: [
      // discover
      { id: 'a-crawl',     layer: 'discover',  label: 'Repo Crawler',       cls: 'crawler',   throughput: '420 repos/day' },
      { id: 'a-classify',  layer: 'discover',  label: 'Asset Classifier',   cls: 'classifier',throughput: '1.4M files/day' },
      { id: 'a-dep',       layer: 'discover',  label: 'Dependency Mapper',  cls: 'mapper',    throughput: '281K edges' },

      // analyze
      { id: 'a-symbol',    layer: 'analyze',   label: 'Symbol Resolver',    cls: 'resolver',  throughput: '466M LOC' },
      { id: 'a-behav',     layer: 'analyze',   label: 'Behavioural Tracer', cls: 'tracer',    throughput: '14K services' },
      { id: 'a-risk',      layer: 'analyze',   label: 'Risk Scorer',        cls: 'scorer',    throughput: '1,400 apps' },

      // plan
      { id: 'a-arch',      layer: 'plan',      label: 'Architecture Planner', cls: 'planner', throughput: '92 plans/wk' },
      { id: 'a-seq',       layer: 'plan',      label: 'Sequencer',           cls: 'planner',  throughput: 'priority queue' },

      // implement
      { id: 'a-author',    layer: 'implement', label: 'Code Author',         cls: 'author',   throughput: '~6.4K PRs/wk' },
      { id: 'a-refactor',  layer: 'implement', label: 'Refactor Specialist', cls: 'author',   throughput: 'pattern-driven' },
      { id: 'a-migrate',   layer: 'implement', label: 'Migration Engine',    cls: 'author',   throughput: 'COBOL / PB / 6i' },

      // verify
      { id: 'a-equiv',     layer: 'verify',    label: 'Equivalence Prover',  cls: 'verifier', throughput: 'differential' },
      { id: 'a-test',      layer: 'verify',    label: 'Test Synthesizer',    cls: 'verifier', throughput: 'gen + run' },
      { id: 'a-sec',       layer: 'verify',    label: 'Security Auditor',    cls: 'verifier', throughput: 'SAST + policy' },

      // govern
      { id: 'a-prov',      layer: 'govern',    label: 'Provenance Ledger',   cls: 'ledger',   throughput: 'signed records' },
      { id: 'a-review',    layer: 'govern',    label: 'Supervisor Console',  cls: 'human',    throughput: 'engineer review' },

      // deploy
      { id: 'a-rollout',   layer: 'deploy',    label: 'Rollout Conductor',   cls: 'deploy',   throughput: 'staged' },
      { id: 'a-rollback',  layer: 'deploy',    label: 'Rollback Sentinel',   cls: 'deploy',   throughput: 'auto-revert' },
    ],
    // High-level inter-layer flows.
    flows: [
      ['discover','analyze'],
      ['analyze','plan'],
      ['plan','implement'],
      ['implement','verify'],
      ['verify','govern'],
      ['govern','deploy'],
      // feedback edges
      ['deploy','discover'],
      ['verify','plan'],
      ['govern','implement'],
    ],
  };

  const tracks = ['Strategy','Discovery','Architecture','Governance','Modernization','Economics','Infrastructure','Operations','Measurement'];

  return { stats, whitepapers, architecture, tracks };
})();
